<?php require('template/header.phtml') ?>

<h3>Welcome to Salford Cars Auctions </h3>

<p><b>Are you looking for a high end car?</b> If you do then you are in right place. We got different auctions
for cars and each auction has 1000s of cars available.<p>
<p>Check Auction details on <b>"Cars"</b> page.</p>
<p>You can view different cars, but you need register before you can place a bid on one of the auction's car.</p>
<p>Registered users will have their own bidding list.</p>
<?php require('template/footer.phtml') ?>
