<?php require('template/header.phtml') ?>

<div id="login">
<form action="" method="post">
    <div class="form-group">
        <label class="control-label col-sm-2">Username:</label>
        <div class="col-sm-10">
            <input type="text" name="username" placeholder="username" value="<?php if (isset($view->username))
            {
                echo $view->username;
            }?>" class="form-control" required="required">
        </div>
    </div>
    <br />
    <!-- Email is required -->
    <div class="form-group">
        <div class="col-sm-10">
            <input type="text" name="email" placeholder="email" class="form-control" id="email">
        </div>
    </div>
    <br />
    <div class="form-group">
        <label class="control-label col-sm-2">Password: </label>
        <div class="col-sm-10">
            <input type="password" name="pwd" placeholder="password" class="form-control">
        </div>
        <div id="code" class="form-group">
            <label class="control-label col-sm-2"><?php if (isset($view->reCaptcha))
                {
                    echo $view->reCaptcha;
                }?></label>
            <div class="col-sm-10">
                <input type="text" name="code" placeholder="Code" class="form-control">
                <input type="hidden" name="finalCode" value="<?php if (isset($view->reCaptcha))
                {
                    echo $view->reCaptcha;
                }?>">
            </div>
    </div>
    <div class="pull-right">
        <div class="button">
            <input type="submit" name="login" value="Login" class="btn btn-success">
        </div>
    </div>
</form>
</div>
<div class="error">
    <p><b>
            <?php if (isset($view->error)) : ?>
                <?php echo $view->error; ?>
            <?php endif; ?>
        </b></p>
</div>

<?php require ('template/footer.phtml')?>
